### ISSUE TITLE
Warning: Declaration of app_yatraffic::saveParams() should be compatible with module::saveParams($data = 1)

### ISSUE THREAD

**Issue by dkrichun** [nick7zmail/MajorDoMo_app_yatraffic#2]
Warning: Declaration of app_yatraffic::saveParams() should be compatible with module::saveParams($data = 1) in /var/www/html/modules/app_yatraffic/app_yatraffic.class.php on line 0

Warning: Declaration of app_yatraffic::install() should be compatible with module::install($parent_name = '') in /var/www/html/modules/app_yatraffic/app_yatraffic.class.php on line 0

**Comment by nick7zmail** [comment]
fixed
